using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;

public class TileInfo : MonoBehaviour
{
    private Tile tile; // The logical data for this tile

    public int x;
    public int y;  

    public bool hasChild{get; private set;} = false;

    /// <summary>
    /// Initializes the TileVisuals with terrain and resources.
    /// </summary>
    /// <param name="terrain">The terrain data for this tile.</param>
    /// <param name="resources">The resources on this tile.</param>
    public void Initialize(Lands land)
    {
        // Create the Tile object
        tile = new Tile(land);
    }
    public void checkChild(){
        if(this.transform.childCount > 0 ){
            hasChild = true;
        }else{
            hasChild = false;
        }
    }
    

    public List<Resources> GetResources(){
        return tile.resources;
    }    

    public void AddResources(Resources resources){
        tile.AddResource(resources);
    }

    public void RemoveResources(Resources resources){
        tile.RemoveResource(resources);
    }
    /// <summary>
    /// Gets the total Coins generated by this tile.
    /// </summary>
    /// <returns>Total Coins.</returns>
    private int GetTotalCoins()
    {
        return tile.CalculateCoins();
    }

    /// <summary>
    /// Gets the total Food generated by this tile.
    /// </summary>
    /// <returns>Total Food.</returns>
    private int GetTotalFood()
    {
        return tile.CalculateFood();
    }

    /// <summary>
    /// Gets the unique code for this tile.
    /// </summary>
    /// <returns>The tile's unique code.</returns>
    private string GetTileNameAndResources()
    {
        return tile.GetTileNameAndResources();
    }

    private void OnMouseDown(){
        UnitSelectManager unitSelectManager = FindFirstObjectByType<UnitSelectManager>();
        if (unitSelectManager.isMoving == true){
            unitSelectManager.MoveAllUnits(this);
        }else{
            Debug.Log($"{tile.GetTileNameAndResources()} Coins: {GetTotalCoins()} Food: {GetTotalFood()}");
        }

    }
}