using Unity.VisualScripting;
using UnityEngine;

public class TileVisuals : MonoBehaviour
{
    private Tile tile; // The logical data for this tile

    public int x;
    public int y;  

    /// <summary>
    /// Initializes the TileVisuals with terrain and resources.
    /// </summary>
    /// <param name="terrain">The terrain data for this tile.</param>
    /// <param name="resources">The resources on this tile.</param>
    public void Initialize(Lands land)
    {
        // Create the Tile object
        tile = new Tile(land);
    }

    public void AddResources(Resources resources){
        tile.AddResource(resources);
    }
    /// <summary>
    /// Gets the total Coins generated by this tile.
    /// </summary>
    /// <returns>Total Coins.</returns>
    private int GetTotalCoins()
    {
        return tile.CalculateCoins();
    }

    /// <summary>
    /// Gets the total Food generated by this tile.
    /// </summary>
    /// <returns>Total Food.</returns>
    private int GetTotalFood()
    {
        return tile.CalculateFood();
    }

    /// <summary>
    /// Gets the unique code for this tile.
    /// </summary>
    /// <returns>The tile's unique code.</returns>
    private string GetTileNameAndResources()
    {
        return tile.GetTileNameAndResources();
    }

    private void OnMouseDown(){
        Debug.Log($"{GetTileNameAndResources()} coins: {GetTotalCoins()} food: {GetTotalFood()} ");

    }
}